@apiBaseUrl =  https://localhost:7152

# GET {{apiBaseUrl}}/weatherforecast/
# Accept: application/json

GET {{apiBaseUrl}}/api/userManagement

###
GET {{apiBaseUrl}}/api/userManagement/1

###
POST {{apiBaseUrl}}/api/userManagement
Content-Type: application/json

{
    "email": "ghostdog09128@gmail.com",
    "lastLoginDate": "2023-10-01T00:00:00",
    "fullName": "Ghost Dog",
    "phoneNumber": "1234567890"
}

