@apiBaseUrl =  http://localhost:5116

# GET {{apiBaseUrl}}/weatherforecast/
# Accept: application/json

GET {{apiBaseUrl}}/api/userManagement

###
GET {{apiBaseUrl}}/api/userManagement/1

###
POST {{apiBaseUrl}}/api/userManagement
Content-Type: application/json

{
    "email": "ghostdog09128@gmail.com",
    "lastLoginDate": "2023-10-01T00:00:00",
    "fullName": "Ghost Dog",
    "phoneNumber": "1234567890"
}

###
PUT {{apiBaseUrl}}/api/userManagement/1
Content-Type: application/json

{
    "email": "@gmail.com",
    "fullName": "Dog",
    "phoneNumber": "990900932"
}

###
DELETE {{apiBaseUrl}}/api/userManagement/1

