@SmartLunch.Api_HostAddress =  https://localhost:7152

# GET {{SmartLunch.Api_HostAddress}}/weatherforecast/
# Accept: application/json

GET {{SmartLunch.Api_HostAddress}}/api/userManagement

###
GET {{SmartLunch.Api_HostAddress}}/api/userManagement/1
